### ISSUE TITLE
Enumeration does not work for ProcessId

### ISSUE THREAD

**Issue by debashish2014** [jonatan1024/clrinject#1]
Hi @jonatan1024 ,

Thank you for authoring such a nice project.

I came accross a bug, that enumeration does not work for process id, however it works for Process Name. I am using a Windows 10 Enterprise edition.

![image](https://user-images.githubusercontent.com/8132553/50881096-92fe2800-1406-11e9-934c-f3f38199a39e.png)

![image](https://user-images.githubusercontent.com/8132553/50881113-a3160780-1406-11e9-9261-d3d726a9787c.png)

Can you please have a look?

**Comment by jonatan1024** [comment]
Hi, it seems to me that you've made an error while typing the PID in.
Top screen PID: 190**46**. Bottom screen PID: 190**64**.

**Comment by debashish2014** [comment]
Hi @jonatan1024 ,

You are right. Sorry, it was my bad. It is working fine if I use the "exe" from Release.

![image](https://user-images.githubusercontent.com/8132553/50949845-d53e6c80-14cd-11e9-8998-f9a4c9337649.png)

However, if I build the project locally and try to run the same, it gives me below error. If you notice, I am getting 2 different errors, running the same command.

![image](https://user-images.githubusercontent.com/8132553/50949891-0f0f7300-14ce-11e9-9249-10cd3b7662a5.png)

It fails with PID as well.

![image](https://user-images.githubusercontent.com/8132553/50950039-b1c7f180-14ce-11e9-92bb-f2e237aee0d6.png)

![image](https://user-images.githubusercontent.com/8132553/50950118-fa7faa80-14ce-11e9-9ba4-688eff829e2b.png)


I am building it with VS 2017 and have retargeted the SDK version. Please see the details below.

![image](https://user-images.githubusercontent.com/8132553/50949945-3ebe7b00-14ce-11e9-9c62-ddbf5a458131.png)

Is there any mistake? I haven't made any code changes though.

**Comment by jonatan1024** [comment]
Please try compiling on Release. I've compiled the project on Debug and it failes the same way as yours. But it works just fine when compiled on Release.

I'll try modify the project settings so it works on Debug too.

Edit:
If you want to use Debug, try to disable "Just My Code". It did the trick for me, so I've disabled it in the lastest commit: 937a20fe8a7c533d8277fa12f240bf451f1857b0

**Comment by debashish2014** [comment]
Yes, it works fine. if I build the application in Release !! 
Also, the fix to disable JMC works well. However, I don't understand, why it is behaving like that.

Thank you. You can close the issue.

**Comment by jonatan1024** [comment]
The [docs](https://docs.microsoft.com/en-us/cpp/build/reference/jmc?view=vs-2017) say:

> When **/JMC** is enabled, the compiler inserts calls to a helper function, `__CheckForDebuggerJustMyCode`, in the function prolog.

So my guess is that the inserted call is not position indepented, so the program jumps somewhere where it shouldn't be and causes access violation exception, crashing the injectee.
